### ISSUE TITLE
Failure to Connect Game & Table

### ISSUE THREAD

**Issue by GermanGump** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#1]
Hi,

I’m having an issue tonight. Just downloaded the Cheat Table files, very excited and I appreciate it a lot! Although, I do follow the steps shown by UC NERD on YouTube to activate and connect the table to the game.. I’m still getting “??” For values on every player and item I attempt to edit. Not too sure what to do about this error!

I’m attaching a link to a screenshot I took while trying to edit a players stats:
https://m.imgur.com/chr8jXL
[](https://m.imgur.com/chr8jXL)

I’d appreciate any help possible!
Thanks again

**Comment by XOverdose** [comment]
Try this:
- Go into player edit, if it isn't unlocked, there is an option under edit player to unlock it in the table
- Now click on the player you want to edit from the list
- Now go into the Cheat Table and everything should show up just fine

It's a little annoying but this has worked just fine for me at least using this method.  You won't be able to see some of the information in game but the information should show up for you on the Cheat Table using this method

**Comment by GermanGump** [comment]
> Try this:
> 
> * Go into player edit, if it isn't unlocked, there is an option under edit player to unlock it in the table
> * Now click on the player you want to edit from the list
> * Now go into the Cheat Table and everything should show up just fine
> 
> It's a little annoying but this has worked just fine for me at least using this method. You won't be able to see some of the information in game but the information should show up for you on the Cheat Table using this method

Hi,

Thank you for your reply! I just tried these steps. Same issue unfortunately. I've attached an image linked below again of whats happening. Not sure how to go about resolving this! 

https://imgur.com/a/TgsSj9Q
