### ISSUE TITLE
Fifa 19 player career

### ISSUE THREAD

**Issue by Adriano030** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#101]
Could you add 100% accomplishments 
and i have a qeustion do you know how to chage my player contract i am 94 rated and only getting 4k a week i would like to edit that

**Comment by Adriano030** [comment]
??

**Comment by xAranaktu** [comment]
`Could you add 100% accomplishments`
Maybe
`how to chage my player contract`
Probably you can edit wage with RDBM 19 in career_users table.

**Comment by Adriano030** [comment]
😩😭

Op do 20 jun. 2019 om 20:08 schreef Paweł <notifications@github.com>
