### ISSUE TITLE
Game Crashes when i load the table

### ISSUE THREAD

**Issue by WolvClaw** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#103]
Game crashes just at the moment the table loads. No Error message or something. It just closes the game.

**Comment by xAranaktu** [comment]
Send cheat table log file.
Log file with today's date is stored inside "logs" folder.
https://i.imgur.com/et8v8dR.png

**Comment by WolvClaw** [comment]
Thanks for the fast reply.

Here is the Log file you asked for.

[log_2019-06-29.txt](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table/files/3341891/log_2019-06-29.txt)

**Comment by xAranaktu** [comment]
Try to uninstall Cheat Engine 6.8.3 and install 6.8.1

**Comment by WolvClaw** [comment]
Didn't solve the problem unfortunately. 
Game still crashes at the moment the table loads.

[log_2019-06-30.txt](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table/files/3343165/log_2019-06-30.txt)

**Comment by xAranaktu** [comment]
Delete these files:
C:/Users/jwolf/Documents/FIFA 19/Cheat Table/data/config.ini
C:/Users/jwolf/Documents/FIFA 19/Cheat Table/data/offsets.ini

**Comment by WolvClaw** [comment]
No change after deleting the files.

Also reinstalled the game now just in case. 
But this also didn't help.

Game keeps crashing.

**Comment by xAranaktu** [comment]
I don't know then what may cause the crash. Sorry.
