### ISSUE TITLE
Youth academy players disappear from team and break squad hub.

### ISSUE THREAD

**Issue by k-bot99** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#104]
Not all of them but when you disappears, the game crashes at squad hub. It usually happen to those i edit with the cheat table but only few.

**Comment by xAranaktu** [comment]
Are you using custom squadfile with created players in it?

**Comment by k-bot99** [comment]
The squad file I am using is FIP 19. I didn't create any players.

**Comment by xAranaktu** [comment]
CT doesn't work well with customized squad files. 
You can try to use RDBM to edit your players.

**Comment by k-bot99** [comment]
thanks
