### ISSUE TITLE
Req: Change Nationalities

### ISSUE THREAD

**Issue by JoseLuisRuedaA** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#105]
In Fifa CM many times the National Team is not considered, maybe if all the players who doesn't have a National Team change their nationality, the world cup, the Euro and the South American will be more interesting. I'm talking about maybe Leon Bailey in Wales with Bale, or Salah with better team mates, Aubameyang playing the World Cup. It would be interesting.

**Comment by xAranaktu** [comment]
You can already change the nationality of any player you want.
Here:
![](https://i.imgur.com/JLoFlD2.png)
or here:
![](https://i.imgur.com/ruTVlQj.png)

**Comment by JoseLuisRuedaA** [comment]
That's true but i mean change the nationalities of all of the players that doesn't have a national team, maybe with a lua user script.

**Comment by xAranaktu** [comment]
Well, yes, it's possible with lua, but this kind of service I provide only for Legend tier Patrons on my [patreon page](https://www.patreon.com/xAranaktu).
