### ISSUE TITLE
Permanent stadium change breaks the stadiums for every match

### ISSUE THREAD

**Issue by yanekyuk** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#107]
I have followed the guide to change my team's stadium permanently but it caused the other team stadiums to change also. I might have made a mistake, but I cannot replicate the issue. Right now I have to find the stadium ids for each team's stadium and change it, save the game, reload the game and start the match every single time. 

TL:DR; Changing home stadium causes a switch in away stadiums also.

**Comment by xAranaktu** [comment]
Because you have frozen the value in CE. It's not a bug. You can also use RDBM to edit these database tables.
