### ISSUE TITLE
Can't execute lua script

### ISSUE THREAD

**Issue by at0myq** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#108]
Hello xArantaktu,
as the title says I can't execute the lua script.

![1cbf4efff7498832e4e86e6c50f5e157](https://user-images.githubusercontent.com/42911608/62315322-63436a00-b495-11e9-92fa-ea1bf3efa7e9.png)

I unzipped the folder, although I also tried the .msi-installer it also didn't work. Reinstalling Cheat Engine helped nothing.

**Comment by xAranaktu** [comment]
Weird... I guess you will need to disable feature which is automatically checking for updates of the CT. 

Put this "helpers.lua" file in "lua/GUI/forms/updateform/"
[helpers.zip](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table/files/3464695/helpers.zip)
