### ISSUE TITLE
Request legends

### ISSUE THREAD

**Issue by extream87** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#11]
Hello king, Thanks for the great work.
Im requesting change player id from academy players. Will be good por example get Legend Ronaldinho replacing an player from our academy. Maybe this is possible editing the id from one academy player to Ronaldinho id. 

Thanks

**Comment by xAranaktu** [comment]
Added in v1.2.8
https://youtu.be/zxrjYBgksvE
