### ISSUE TITLE
CPU vs CPU (auto subs by CPU)

### ISSUE THREAD

**Issue by LickinPukki** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#111]
Hi xAranaku,

Thanks for the good work. I have been using the Cheat Table since FIFA 18, solely to enjoy watching CPU vs CPU in career mode. But in FIFA 19 CT, I couldn't find an option to stop the CPU from auto substituting the players. I would like to take control of the substitution. Am I missing the option? Thanks

**Comment by xAranaktu** [comment]
In-Game Hacks -> Home/Away Team -> Home/Away - Disable Substitutions 
https://i.imgur.com/arTmdb1.png

**Comment by LickinPukki** [comment]
Thanks, really appreciate your help
