### ISSUE TITLE
Access Violation on trying anything

### ISSUE THREAD

**Issue by amordoch** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#112]
Just trying to edit a player and I just downloaded this. I'm starting the table as in FIFER's tutorial and it seems to be hooking into the FIFA process, but any time I try anything at all, the Lua console comes up and gives a bunch of access violation errors. I tried googling the error but didn't find anything relevant to FIFA.
Screenshot:
![image](https://user-images.githubusercontent.com/6799046/63815956-5daa3a00-c904-11e9-8fb2-16694ef1bc17.png)

**Comment by xAranaktu** [comment]
It's a bug in Cheat Engine 7.0, you need to use other version. 
I recommend to download and install Cheat Engine 6.8.1:
https://github.com/cheat-engine/cheat-engine/releases/download/v6.8.1/CheatEngine681.exe
