### ISSUE TITLE
Player Career Head Model Error

### ISSUE THREAD

**Issue by ANicol94** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#16]
Hi,

After changing the Head Asset ID for my create player, after the first game played or after saving and reopening career save the head ID resets to 0 showing a completely different Head ID. 

Entered 152729 into Head asset ID. I followed the instructions changing the quality head to 1 and the other 2 options to 0.
--

--

**Comment by xAranaktu** [comment]
> You need to know that this cheat table is designed for manager career mode. Scripts may or may not work in player career mode, especially if you are using player created by your own.
