### ISSUE TITLE
Jersey number

### ISSUE THREAD

**Issue by congmasosyu** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#17]
Is this version be able to edit the jersey number of player?
Not in "Squad Hub" but "Edit Player" where can edit players from other clubs
In FIFA 18 version, it can be find in "Editing Player/Edit Player/Information/Jersey number"
I don't find it on FIFA 19 cheat table, hope it will be added on a newer version

**Comment by xAranaktu** [comment]
Jersey Number can be changed in FIFA Database ->Database Tables -> teamplayerlinks Table

**Comment by congmasosyu** [comment]
Thanks. I found it but the number didn't change
When I edit the player, the number on cheat table is (X-1)
I changed and "Apply & Exit" after it was still the same
Should I click the box?

**Comment by xAranaktu** [comment]
In this case editing should be done while you are in squad hub in-game. If it will not work then editing jersey number may be not possible at this moment.
