### ISSUE TITLE
How can I change shoes?

### ISSUE THREAD

**Issue by realkeirametz** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#21]
How can i change my player's shoes? I'm playing player career mode and I can't choose all shoes on edit pro. So, I want to change my shoes but I don't know the other shoes' codes. Can u help me?

**Comment by xAranaktu** [comment]
To change shoe model you need to change 'shoetypecode' in FIFA Database > Player Tables > Accessories
Boot ids can be found here -> [FIFA 19 IDs](https://docs.google.com/spreadsheets/d/1eYx5j7FZwlaPKymv3_G-ezZKtfWmQ6hwjXukAfqYoto/edit?usp=sharing) and some other are also on [Discord](https://discordapp.com/invite/cbQePsR) in '#showoffyourcreations' channel

However, I don't know if it will work in player career mode.
