### ISSUE TITLE
Change player portrait table and celebrations?

### ISSUE THREAD

**Issue by pakiet96** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#22]
Hi, love the table and your work, just a suggestion to see if its possible to implement this into the cheat table.
Change player portrait and maybe celebrations (maybe celebrations exist but I'm just too blind to find it).

Anyways, thank you very much!

**Comment by xAranaktu** [comment]
Portrait can be only changed if playerid is higher than 280000, which means you can't change it for real players, will work only for these which was generated by the game. To do the change you need to edit "headtypecode" and/or "haircolorcode".

As far as I remember, celebrations can be changed by editing 'finishingcode1' in Database Tables->Players Table->Other. List of FIFA 19 IDs is available here -> [Google Drive](https://docs.google.com/spreadsheets/d/1eYx5j7FZwlaPKymv3_G-ezZKtfWmQ6hwjXukAfqYoto/edit?usp=sharing)

**Comment by pakiet96** [comment]
Hi thanks, this thought came up because I wanted to change the portrait of the regens (since I edited their old head models back, but the portrait stayed the ugly generic regen one), so it could still work?. Thanks for the answer!

**Comment by xAranaktu** [comment]
Yes, as I said you need to change headtypecode and haircolorcode. The easiest way will be probably copying these values from a player that already have a portrait that you want to use.
