### ISSUE TITLE
 Update 22.01.2019

### ISSUE THREAD

**Issue by Kakoboss** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#25]
Good afternoon. had an update day 22 of that month. option "in-games hacks does not open.update please> thx

**Comment by xAranaktu** [comment]
Already fixed in v1.0.11
[Release schedule](https://docs.google.com/spreadsheets/d/1EsYf4I4oDD6kw5jTGTFsv7rR1qL-Oausd1ZRbbSWm84/edit#gid=0)
