### ISSUE TITLE
Player career mode

### ISSUE THREAD

**Issue by realkeirametz** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#26]
I'm playing in Ankaragücü for 5 seasons but my contract still not ended. I want to play in different team but when my team put me to transfer list nobody is making an offer to me...  I'm playing very well my overall is 94 but still playing in Ankaragücü... Can I change my team with this Cheat Table? Or what can I do? Please help me.

**Comment by xAranaktu** [comment]
You need to decrease your ovr.
