### ISSUE TITLE
Changing My Manager name

### ISSUE THREAD

**Issue by Chandrilbasu** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#27]
hello Aranaktu! I have created a manager 5 seasons ago and the name is Mr.Manager...I want to change the name , is there any way ?
Off Topic : thank you for your hardwork...you are amazing

**Comment by xAranaktu** [comment]
You can change the name in "career_users" database table with [Revolution DB Master 19](http://soccergaming.com/index.php?threads/revolution-db-master-19.6466139/)
