### ISSUE TITLE
Block Offers

### ISSUE THREAD

**Issue by HusseinFIFA19** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#28]
Can I block offers others team's players in this cheat table?
For example, I played a career manager with Barcelona. In the first transfer window in January I repeat in January Sergio Ramos and Marcelo leaves Real Madrid :| or Kylian Mbappe go to Dortmund I want to stop dummy transfer like that.

**Comment by xAranaktu** [comment]
At this moment it's not possible.

**Comment by HusseinFIFA19** [comment]
Still not possible to stop dummy transfer in cheat table.

**Comment by Nigelos** [comment]
As a temporary workaround, you can possibly transfer them back by 1)toggling the Allow Transfer Approach script in Cheat Table, 2) give yourself a generous transfer budget, 3) buy that player yourself (e.g. buying Mbappe from Dortmund) and 4) find a worthless player at PSG and then use Mbappe in a Swap Player transfer for that player. If PSG ask for a player in a different position, just take note of that position, change Mbappe's position to that required position using the Cheat Table and then trying again with another transfer approach after the 1 week cool down finishes. After completing Mbappe's transfer back to PSG, just revert his position back to the original one and then sell/release/keep the player you received in the swap transfer.
