### ISSUE TITLE
Fifa 19 Request

### ISSUE THREAD

**Issue by bradgeezer** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#30]
Hello mate,
Really enjoying the cheat table you created to use on fifa 19. I have only ever played Fifa on Xbox and it got to the point where i couldn't justify paying/playing the game anymore as Fifa have got so lazy with career mode since ultimate team was released. You've made the game worth playing again. 10 years ahead of the game in terms of how fast Fifa update what they should of done a decade ago.
if you updated nothing else it wouldn't bother me as i'm already extremely happy with what you've done but for the past 7 or 8 years I always play with the Australian national squad on career mode but using a local club in the English league. I noticed on the cheat table that you have team badge, team kits and even team name on the scripts. Will you be going ahead with that and making it possible to use? It would be insane to create my own team which fifa use to have years ago but took off and each year change my clash kit making the game even more realistic, if you cannot that it also completely fine I just thought I'd ask. Thank you :)

**Comment by xAranaktu** [comment]
It will be probably never possible. I mean, not with cheat table. You can actually only permanently change these things which saves when you save your career. Teamname is stored somewhere else, not saying about textures and assets.

But overall it might be possible to edit existing teams when frosty tool will fully support FIFA 19.

**Comment by bradgeezer** [comment]
Thank you for replying and fair enough, Thought I'd ask.
As for the transfer configuration, how does that work and does it work? My take on it is it gives me the power to stop dumb transfers, switch players to teams i want as in salah going to real madrid? Can i stop this/transfer for him back to liverpool?



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by xAranaktu** [comment]
It's in FIFA 19 cheat table only because it was also in FIFA 18 cheat table. Since last year EA has removed a lot of configurable settings from transfer.ini and transfers.ini config files. You can try to edit the script by yourself, but probably you will not achieve what you want.
