### ISSUE TITLE
Fifa 19 request

### ISSUE THREAD

**Issue by kelincipetarung** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#31]
hi xAranaktu, i'm really enjoying your cheat table. i want to make a request, can you make a change player squad role code? like you want to change your player from "crucial" to a "sporadic" role, thanks

**Comment by xAranaktu** [comment]
It's possible, but you need to negotiate new contract with a player. 
Use Contract Negotiation script:
![](https://i.imgur.com/wzaCesP.png)

https://www.youtube.com/watch?v=K5CxZVT9geQ
