### ISSUE TITLE
stop the retirement  

### ISSUE THREAD

**Issue by alirezapk232** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#32]
Hello king, Thanks for the great work
can you please add an option to stop the main year count at the top so the career mode doesn't end  continues forever? 
i guess its not that hard like putting mario in the game , its just an address .
or maybe there is some other ways to stop the manager retirement i dont know but i believe you can figure it out .
i just made a cool team with new players that i scouted from all over the world and cant wait to start the next season and suddenly boom you are retired . thats sucks i just want to go forever to see the new players and grow my own as well
anyway . thank you in advance and sorry for my bad english

**Comment by xAranaktu** [comment]
You can achieve this by editing 'seasoncount' in 'career_users' database table. Activate 'seasoncount = 1' script and save your career. 
![](https://i.imgur.com/wQb7Mv3.png)

Or edit this field in database with RDBM 19
![](https://i.imgur.com/zRy7v2x.png)

**Comment by alirezapk232** [comment]
oh. ok . thanks a lot. ill try it out for sure . your awesome thanks 👍
