### ISSUE TITLE
Editing haircuts on created players

### ISSUE THREAD

**Issue by skeetmask** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#33]
Hey, i just wanted to say congrats on the cheat engine, it's helped me and a lot of people out a lot so far and i wish you good luck in the future.
I don't really have any complaints but just a somewhat inconvinience that i've come across, i play on a career mode with created players made from the 'Create Player' option in the settings, ive noticed that i can edit them properly as in give them traits, and change their overall look mostly like skin color, height, body type and all that, but it appears i can't change the haircut of created players, even though i can change it on other players with generic faces, i was wondering if you could perhaps look into it?
Cause i've already reinstalled the cheat engine and that didn't work, and one other user in the comment section had the same issue.
Once again, thanks for making this wonderful cheat engine! And good luck in the future.

**Comment by xAranaktu** [comment]
Well, as mention in [readme ](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table/blob/master/README.md) file, cheat table is designed for manager career mode. It means that I don't test any functionality in player career mode/created players. EA is using different logic for created players. For now, I don't have time to make special scripts for this game mode.
