### ISSUE TITLE
Hey, got this issue when i launched the latest version (v1.1.2)

### ISSUE THREAD

**Issue by misterchow05** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#34]
Error:.\lua/helpers.lua:62: attempt to index a nil value (global 'LOGGER')

When I tried to activate a script after the aforementioned error:
Check process has failed. FIFA_PROCESS_NAME is nil

I have selected the FIFA19 process in the cheat engine.

**Comment by xAranaktu** [comment]
Cheat table is now automatically attaching to the game. Don't do it by yourself. Did you read https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table/blob/master/README.md#getting-started ? :p
