### ISSUE TITLE
The table failed to load : data error

### ISSUE THREAD

**Issue by doha2** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#36]
Hey man

I've previously used your tables no problem (thanks for making them) but every time I try lately I get a data error message in CE when trying to open them. Latest CE 6.8.3 and the latest edition of your table you released 2 days ago. Doesn't matter if CE is being run as admin or not. I've selected the box to always let it run LUA scripts. W10 x64.

**Comment by xAranaktu** [comment]
Send me log file from logs folder and screenshot from lua engine console when error occurs.

**Comment by doha2** [comment]
I don't have a logs folder under the CE main folder. It doesn't crash, it just throws up a warning message which when cancelled goes back to normal CE.

**Comment by xAranaktu** [comment]
Did you unzipped downloaded archive? 
https://i.imgur.com/7xiFXn4.gifv

And again, show me screenshot of an error, because I have no idea what are you talking about.

**Comment by doha2** [comment]
![untitled99](https://user-images.githubusercontent.com/47787180/53164825-04fe8b00-35c9-11e9-88de-bc26809581c8.png)

**Comment by xAranaktu** [comment]
GUI is not working in v1. 1.2 after latest game update. It's fixed in v1.1.7.
[Release Schedule](https://docs.google.com/spreadsheets/d/1EsYf4I4oDD6kw5jTGTFsv7rR1qL-Oausd1ZRbbSWm84/edit#gid=0)
