### ISSUE TITLE
table failed to load

### ISSUE THREAD

**Issue by jacobcass97** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#37]
[log_2019-02-19.txt](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table/files/2881168/log_2019-02-19.txt)
![untitled](https://user-images.githubusercontent.com/32766083/53034660-ae466380-3499-11e9-8766-5eb31738ae6f.jpg)

the above error message is what i get when i try to load the cheat table for fifa 19 but i have unziped the fifa 19 cheat table using winrar

**Comment by xAranaktu** [comment]
Where did you unziped it? Do you have 'lua' folder there? Show me screenshot ;d
Also, does v1.1.4 work? https://www.patreon.com/posts/fifa-19-cm-cheat-24742945

**Comment by jacobcass97** [comment]
![lua](https://user-images.githubusercontent.com/32766083/53085127-396e3a80-3528-11e9-8021-dd56159e6584.jpg)

**Comment by jacobcass97** [comment]
v1.1.4 does not work either

**Comment by jacobcass97** [comment]
![lua 2](https://user-images.githubusercontent.com/32766083/53085315-97028700-3528-11e9-9803-56a1219f7a84.jpg)

**Comment by xAranaktu** [comment]
Send file from logs folder.

**Comment by jacobcass97** [comment]
[log_2019-02-20.txt](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table/files/2885386/log_2019-02-20.txt)

**Comment by xAranaktu** [comment]
Okay. Looks like you don't have 'cheat table' folder in Documents\FIFA 19 folder. Open cmd and drag&drop 'create_dirs.bat' there and press enter. If there will be any error in cmd then make screenshot and send it here.

**Comment by jacobcass97** [comment]
hai my cmd prompt does not open it appears and disappears at a split second when i try to run my command prompt so i created a new user and ran the cmd from there here is what i got
![fifa 19 bat file](https://user-images.githubusercontent.com/32766083/53142574-7420b300-35ba-11e9-98aa-81d523584b2a.jpg)

**Comment by xAranaktu** [comment]
Can you run cheat table now. It just failed to copy temple images, but folder has been created. Send log file again if it there is any problem.

**Comment by jacobcass97** [comment]
![img-4913](https://user-images.githubusercontent.com/32766083/53148790-d20cc500-35d1-11e9-946e-1c0906584aab.JPG)
[log_2019-02-21.txt](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table/files/2887988/log_2019-02-21.txt)

**Comment by jacobcass97** [comment]
this is what i get when i try to run the cheat table after trying the above mentioned method suggested by you

**Comment by flavius49** [comment]
![dede](https://user-images.githubusercontent.com/47866877/53193494-c34a0080-3619-11e9-853f-282a70eda779.png)

**Comment by flavius49** [comment]
i have this problem..please help

**Comment by tpbnick** [comment]
![image](https://user-images.githubusercontent.com/49327729/55662418-e18e4900-57e0-11e9-905a-4e2dd901d681.png)
I get the exact same error.  I have tried deleting the cheat table folder in the FIFA 19 folder in my documents and I have also reinstalled Cheat Engine.  This has persisted since the GUI was released.

**Comment by FIFER-Mods** [comment]
Just use the .msi installer. You can get it from Patreon.

>

**Comment by tpbnick** [comment]
Just tried that, I get the same error.  I deleted the old cheat table folder in my FIFA folder as well.

**Comment by FIFER-Mods** [comment]
Send me your logs file.

**Comment by tpbnick** [comment]
How do I do that?  Sorry!

**Comment by FIFER-Mods** [comment]
Go into your "logs" folder in your cheat table folder and send me the
latest one (from the time you had the error)

**Comment by tpbnick** [comment]
![image](https://user-images.githubusercontent.com/49327729/55669967-cdcbfc80-584b-11e9-831b-acd180fdf023.png)
I fixed it.  My Antivirus labeled Cheat Engine as an application that changes protected files.  Thanks for trying to help!  I appreciate it.
