### ISSUE TITLE
Fixx

### ISSUE THREAD

**Issue by ShiFttttt** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#38]
The 1.1.2 version doesn't work

error:.\lua/helpers.lua62: attempt to index a nil value (global 'LOGGER')

**Comment by xAranaktu** [comment]
You have probably didn't allowed cheat engine to execute the lua script at startup. Read https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table#getting-started

**Comment by ShiFttttt** [comment]
I did allow cheat engine to run the lua
