### ISSUE TITLE
AOB_DatabaseRead AOBScanModule error Issue

### ISSUE THREAD

**Issue by UIJONGKI** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#39]
After downloading cheat engine table v1.1.12, I'm having trouble with opening database table.
Whenever trying to ope database table, It says "AOB_DatabaseRead AOBScanModule error".
And, when I open/close the script of database table, it says "not all code is injectable. (Lua error in the script at line 3:.\lua/helpers.lua:92:Could not find valid offset for)".
How can I solve it? I'm so struggling now..

**Comment by xAranaktu** [comment]
You can't. 'Database tables' script is not working with latest game update.
