### ISSUE TITLE
AOB_DatabaseRead error happening on newest patch

### ISSUE THREAD

**Issue by XOverdose** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#40]
Hello, so since the latest patch of FIFA 19, released today, I have started receiving the ADB_DatabaseRead ADBScanModule error every time I launch the cheat table.  However, it seems like the code of FIFA 19 has been changed in FIFA 19 itself, as I have tried V1.11 and V1.12 and the completely same issue occurs.  I see at least 5 people complain about the completely same issue, though a lot of them are on the last patch when they originally submitted their issue.  

I don't know if this is a problem with the latest premium release, as I am not a Patron and I never plan on becoming one, due to the waste of money you are giving to your favourite creators at the end of each month and in my eyes, I am trying to save money, if you see it that way.  Anyway, I'll wait potentially for the latest release.

**Comment by xAranaktu** [comment]
Database Tables script is not working with latest game update. Will be fixed in v1.1.7.

**Comment by xAranaktu** [comment]
Problem fixed in v1.1.7
[Release Schedule](https://docs.google.com/spreadsheets/d/1EsYf4I4oDD6kw5jTGTFsv7rR1qL-Oausd1ZRbbSWm84/edit#gid=0)
