### ISSUE TITLE
database table not opening after new update

### ISSUE THREAD

**Issue by Chandrilbasu** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#41]
bro database table isnt opening after new update

**Comment by xAranaktu** [comment]
Problem fixed in v1.1.7
[Release Schedule](https://docs.google.com/spreadsheets/d/1EsYf4I4oDD6kw5jTGTFsv7rR1qL-Oausd1ZRbbSWm84/edit#gid=0)
