### ISSUE TITLE
Lua script error

### ISSUE THREAD

**Issue by xXpirojoXx** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#42]
have a lua script error when i open the career table.

**Comment by JOols87** [comment]
Same problem here. I checked for new version of cheat table this afternoon cause i couldn't open "Data Base Table" after official patch. I took a screenshot of what happening when i load the table in cheat engine.
[https://image.noelshack.com/fichiers/2019/08/3/1550688101-capture.jpg](url)
I don't know how to check log to send it.

**Comment by xAranaktu** [comment]
You need allow cheat engine to execute lua script at startup.
[Read Getting Started](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table#getting-started)

**Comment by ShiFttttt** [comment]
That's not the case at all, It happens even if you allow cheat engine to execute it

**Comment by xAranaktu** [comment]
Open lua console (CTRL+ALT+L) and execute there:
`require 'lua/main';`
And try to active script. Same error?

You can also edit config.ini. Go to Documents\FIFA 19\Cheat Table\data and open 'config.ini' with notepad and enable debug mode.
![](https://i.imgur.com/wrnfTOu.png)
`debug_mode=true`

**Comment by ShiFttttt** [comment]
There is no \cheat table\data only \cheat table\cache.

And I tried to execute that and activate the script again, but I got the same lua error. Can you not just release the 1.1.3 for us? It's clear that the 1.1.2 doesn't work for anyone so we can't even use the table at all

**Comment by xAranaktu** [comment]
v1.1.3 will not work either in your case. ;) I've just run v.1.1.2 and I don't have error which is on the screenshot above.

Create 'data' folder by yourself then. After you run cheat table file should be created. And then edit it.
Maybe you also deleted 'logs' folder? It should be in the same directory where FIFA19.CT is.
![](https://i.imgur.com/icL9Y6u.png)

**Comment by JOols87** [comment]
> "You need allow cheat engine to execute lua script at startup." 

I always tick "always allow"

> "There is no \cheat table\data only \cheat table\cache."

I can confirm. Unless there is a tip to make it appears, there is no "cheat table" folder in Document/Fifa 19.

> Create 'data' folder by yourself then. After you run cheat table file should be created. And then edit it.

Nothing appears in this handmade folder after run cheat table.

> Maybe you also deleted 'logs' folder? It should be in the same directory where FIFA19.CT is.

There is no "logs" folder

![capture2](https://user-images.githubusercontent.com/47829760/53121525-b0b9c380-3554-11e9-8e29-f082a1ff870c.JPG)

**Comment by xAranaktu** [comment]
Okay, now I get it. You have cloned repo which don't have logs folder. GitHub deleted all empty files and folders :( 
I've added missing folder to the repository, but better download table from [releases](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table/releases) anyway

**Comment by ShiFttttt** [comment]
It works for me now, Thank you

**Comment by JOols87** [comment]
Ok… I finally found "cheat table" folder but not in Document/fifa 19 which is the place where fifa 19 files and saves are, but in user/nameuser/documents/fifa19, "cheat table is alone here" with a "cache" folder inside.

**Comment by xAranaktu** [comment]
Well, on Windows 10 "C:\Users\Pawel\Documents\FIFA 19" is the same path as "Documents\FIFA 19". :P
