### ISSUE TITLE
cannot open database tables

### ISSUE THREAD

**Issue by viserion3007** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#43]
why is everytime i want to open the database tables it always said AOB_DatabaseRead AOBScanmodule error 
![image](https://user-images.githubusercontent.com/47847979/53155232-35592000-35ef-11e9-9ef5-c2be1a3be639.png)

**Comment by ttr1der** [comment]
same here

**Comment by lukemw1** [comment]
Yeah I also have this issue

**Comment by xAranaktu** [comment]
GUI is not working in v1. 1.2 after latest game update. It's fixed in v1.1.7.
[Release Schedule](https://docs.google.com/spreadsheets/d/1EsYf4I4oDD6kw5jTGTFsv7rR1qL-Oausd1ZRbbSWm84/edit#gid=0)

**Comment by celal198** [comment]
still same problem .

**Comment by Eshesheshesh** [comment]
Yup the problem exists for all the versions
