### ISSUE TITLE
the lua error..

### ISSUE THREAD

**Issue by xXpirojoXx** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#44]
![error](https://user-images.githubusercontent.com/47829431/53196040-c3380980-35f5-11e9-8ca4-db054c0a19a3.JPG)

**Comment by xAranaktu** [comment]
Did you unzipped the archive with winrar?
https://i.imgur.com/2R9SiMW.gifv

**Comment by xXpirojoXx** [comment]
yes

**Comment by xAranaktu** [comment]
Show me screen from folder where you have unzipped it. Generally lua folder must be in the same directory where cheat table is.

**Comment by mmp5453** [comment]
I have the same issue.
"Error:.\lua/helpers.lua:68: attempt to perform arithmetic on a nil value (local 'base_addr')"
Also, I cannot access the databases within the Cheat Table.
"AOB_DatabaseRead AOBScanModule error. Try to restart FIFA and Cheat Engine."
(Restarting has not done anything btw)

**Comment by xXpirojoXx** [comment]
the error of lua has been solved, but there is another error> AOB_DatabaseRead AOBScan Module error. Try to restart fifa and cheat engine. i restarted, but nothing happened

**Comment by xAranaktu** [comment]
After last game update database tables script (and GUI) is not working on all CT versions below v1.1.7. 
v1.1.7 will be released for everyone on 27.02.2019
[Release Schedule](https://docs.google.com/spreadsheets/d/1EsYf4I4oDD6kw5jTGTFsv7rR1qL-Oausd1ZRbbSWm84/edit#gid=0)
