### ISSUE TITLE
This happens when trying to open database tables

### ISSUE THREAD

**Issue by Arcanine878** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#45]
![image](https://user-images.githubusercontent.com/41586142/53218325-9c102500-3653-11e9-8120-37f2da415d8a.png)

**Comment by MattyYun** [comment]
I have same issue.
I heard "'Database tables' script is not working with latest game update.", right?
v1.1.3 plans to be released on 22.02.19, will that issue be corrected?

**Comment by xAranaktu** [comment]
GUI is not working in v1.1.2 after latest game update. It's fixed in v1.1.7.
[Release Schedule](https://docs.google.com/spreadsheets/d/1EsYf4I4oDD6kw5jTGTFsv7rR1qL-Oausd1ZRbbSWm84/edit#gid=0)
