### ISSUE TITLE
Restart Required?

### ISSUE THREAD

**Issue by Porsal01** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#46]
Whenever I try to launch the table I get the following error,

Restart required, getOpenedProcessID != 0

**Comment by xAranaktu** [comment]
Don't attach to the process by yourself. Cheat Table will do it for you.
Read [Getting Started](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table#getting-started)
