### ISSUE TITLE
Fifa 2019 Cheat Table 1.1.4 Error

### ISSUE THREAD

**Issue by EgeOncel77** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#47]
I have an original game (latest update) I download latest version of Cheat Engine and Cheat Table and read and follow the subtances on Getting Started but i go to Scripts/Databases tables it says '' AOB_DatabaseRead AOBScanModule error. Try to restart FIFA and Cheat Engine'' please help me!!!

Sorry for my English.

**Comment by xXpirojoXx** [comment]
I have this problem too.

**Comment by xAranaktu** [comment]
After last game update database tables script (and GUI) is not working on all CT versions below v1.1.7. 
v1.1.7 will be released for everyone on 27.02.2019
https://docs.google.com/spreadsheets/d/1EsYf4I4oDD6kw5jTGTFsv7rR1qL-Oausd1ZRbbSWm84/edit#gid=0

**Comment by ollywoodnight** [comment]
Great news Aranaktu! I will keep an eye out for the update on 27th. Keep up the good work, CM wouldn't be the same without you!
