### ISSUE TITLE
mini face issue

### ISSUE THREAD

**Issue by TimoWerner** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#48]
ayo wassup homie...them generic minifaces looks like pimps man..is there a way i can change them minifaces with CT..?

**Comment by xAranaktu** [comment]
If you change headtypecode or haircolorcode in "Database Tables" -> "Players Table" miniface will change.
Same thing can be done with GUI. 
https://i.imgur.com/40LkPOT.gifv
