### ISSUE TITLE
Training everyday issue

### ISSUE THREAD

**Issue by tari02** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#5]
Hi,

after new update it does not seem like 'Training everyday' attribute is working anymore. Every other feature from 'Players training' works, but 'Training everyday' simply cannot be checked. Strange.

Any idea what has happened or can it be solved somehow?

edit: same for 'Unlimited training sessions'. Of course by update I mean Fifa's update. Before I was playing on v1.02 of Cheat Table, now I've switched to the newest one to see if it works, but no, it doesn't.

**Comment by xAranaktu** [comment]
I'm gathering list of all not working scripts here:
https://www.patreon.com/posts/latest-game-22247079

**Comment by tari02** [comment]
Great. I see that Players training is already there.

Thanks a lot for your fast reply :)
