### ISSUE TITLE
Manager Head

### ISSUE THREAD

**Issue by amanciofael** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#50]
Hi, I can not put my face on my coach in my new career mode. in my old I managed to put with the version of Cheat Engine 6.8.1 and Cheat Tables 1.0.3 but now I can not because the square where it has DATABASE TABLE does not open. I click and click on it but it does not open. I downloaded the Cheat Engine version 6.8.3 and the last version of Cheat Tables opened but when I clicked the "??" she would not open for me to put the technician ID. Do you have any new procedure to put the face on the technician in FIFA?

**Comment by xAranaktu** [comment]
https://docs.google.com/document/d/1LUM2z1cO_RcS2k91Jpea04lhQW33cjOO1-2BXeE-CSM/edit

**Comment by amanciofael** [comment]
Thank you Aranaktu, you best!
________________________________
De: Paweł <notifications@github.com>
Enviado: terça-feira, 26 de fevereiro de 2019 13:49
Para: xAranaktu/FIFA-19---Career-Mode-Cheat-Table
Cc: amanciofael; Author
Assunto: Re: [xAranaktu/FIFA-19---Career-Mode-Cheat-Table] Manager Head (#50)


https://docs.google.com/document/d/1LUM2z1cO_RcS2k91Jpea04lhQW33cjOO1-2BXeE-CSM/edit

-
Você está recebendo isso porque você escreveu o tópico.
