### ISSUE TITLE
can not open FIFA19.CT

### ISSUE THREAD

**Issue by feelsodesperate** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#51]
when I open FIFA19.CT nothing happens and when I click on it it says Cheat Engine stopped working

**Comment by xAranaktu** [comment]
Cheat engine stops responding because it's waiting until you enter main menu in game.

**Comment by feelsodesperate** [comment]
OK but now it says
AOB_DatabaseRead AOBScanModule error. Try to restrart FIFA and Cheat Engine

**Comment by feelsodesperate** [comment]
and no matter how many times I restart the game and Cheat Engine it gives that error again

**Comment by xAranaktu** [comment]
After last game update database tables script (and GUI) is not working on all CT versions below v1.1.7. 
v1.1.7 is already released to patrons, and will be released for everyone on 27.02.2019

**Comment by feelsodesperate** [comment]
OK thanks
