### ISSUE TITLE
Failed to execute lua

### ISSUE THREAD

**Issue by KarlWebster97** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#52]
![image](https://user-images.githubusercontent.com/19327709/53443499-c2431580-3a03-11e9-849b-9784f18fd4f1.png)

(Lua is allowed to run as per the install guide)

**Comment by KarlWebster97** [comment]
![image](https://user-images.githubusercontent.com/19327709/53443684-28c83380-3a04-11e9-82ee-30c4e9d1cac0.png)

When I do what that error says, I get the above

**Comment by xAranaktu** [comment]
After last game update database tables script (and GUI) is not working on all CT versions below v1.1.7. 
v1.1.7 is already released to patrons, and will be released for everyone on 27.02.2019
