### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ikotaner** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#53]
Hi,

first, thank you for the great work so far. Really let me enjoy the game much more.

My issue:

1.16 ( tried ealier Versions too )

I receive the following error : ( please review the screenshot )

**Comment by ikotaner** [comment]
<img width="470" alt="fifa 19 cheat table 1 16 error" src="https://user-images.githubusercontent.com/48057608/53493305-5ca26800-3a9b-11e9-9584-5b5e279bf9c3.PNG">

**Comment by ikotaner** [comment]
Also when I try to Access the Database Script in Version 1.09 it does not load any more. 

Before the last Fifa Update it worked perfectly and I never experienced an issue.

Thanks in Advance for your support.

**Comment by DennisOlgun** [comment]
According to the author this issue is resolved in version 1.1.7.

**Comment by ikotaner** [comment]
Thank you for the Information. Good News! 

But is this issue with the data base script which does not load anymore caused by the Fifa update or anything other?

Interesting is that all the other scripts are working for me. Just the data base not.

**Comment by DennisOlgun** [comment]
i'm not certain since i'm not really familiar with the technical side of this issue, it might be that EA patched something which prevents the older table from editing anything in that specific section of the game code.

**Comment by xAranaktu** [comment]
> Thank you for the Information. Good News!
> 
> But is this issue with the data base script which does not load anymore caused by the Fifa update or anything other?
> 
> Interesting is that all the other scripts are working for me. Just the data base not.

As you noticed by yourself, it's because of the last update. :) It happens from time to time with other scripts, but it's first time that "Database Tables" script stopped working after game update. 
Anyway, it's fixed in v1.1.7
