### ISSUE TITLE
Change The Shoes

### ISSUE THREAD

**Issue by amanciofael** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#56]
I am no longer able to change the players' boots for Cheat Engine when I click on the database Table does not open.Can modify by RDBM and how do you do? Thank you.

**Comment by xAranaktu** [comment]
It depends which game version you have and which cheat table version are you using. If you have latest patch on Origin then you need to use cheat table v1.1.7

**Comment by amanciofael** [comment]
my version of FIFA is from February 14, 2019
Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by xAranaktu** [comment]
So try Cheat Table v1.1.6 or Cheat Table v1.1.7. If any of these will not work then get familiar with [Getting Started](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table#getting-started)

If you get any error then send screenshot from "Lua engine" console and send log file from logs folder.

**Comment by amanciofael** [comment]
Ok, thank you.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
