### ISSUE TITLE
1.17 Error

### ISSUE THREAD

**Issue by abilflyis** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#57]
Whenever I try to open it, I get this error message
![ct issue](https://user-images.githubusercontent.com/47877152/53521067-35e92f00-3aa5-11e9-9973-b7f512d6f867.PNG)

**Comment by abilflyis** [comment]
just fyi I did unzip it to a folder on my desktop

**Comment by xAranaktu** [comment]
You don't have Cheat Table folder in "C:/Users/TSV/Computers/Documents/FIFA 19". Try to run "create_dirs.bat". If it will not help then unzip [this file](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table/files/2916259/Cheat.Table.zip) there.
