### ISSUE TITLE
I cannot open database table

### ISSUE THREAD

**Issue by Eshesheshesh** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#58]
![image](https://user-images.githubusercontent.com/48075141/53535079-8609d500-3b29-11e9-9926-5263d50fb541.png)
I can't seem to check mark on some of the options. Database Table, for instance. This issue persists for newer versions of cheat table also -AOB_DatabaseRead AOBScanModule error Issue I get this error

**Comment by xAranaktu** [comment]
You need to use Cheat Table v1.1.7
