### ISSUE TITLE
Cannot change players in GUI

### ISSUE THREAD

**Issue by Colisky** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#59]
Then i try to open GUI i get this error message
![image](https://user-images.githubusercontent.com/48086046/53554769-946be700-3b51-11e9-909b-9dc4c4734c06.png)
pls help

**Comment by xAranaktu** [comment]
Try to run "create_dirs.bat"
If it will not help then send log files from logs folder.

**Comment by Colisky** [comment]
No it doesn't help
[log_2019-02-28.txt](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table/files/2916287/log_2019-02-28.txt)

**Comment by xAranaktu** [comment]
Something is preventing CE from downloading image assets from internet. 
Try to:
1. Run Cheat Engine as administrator.
2. Check your firewall settings, maybe it's blocking CE
3.  Reinstall Cheat Engine.

I'm not able to help in any other way.

**Comment by Colisky** [comment]
Thank you
