### ISSUE TITLE
Free and unlimited player release

### ISSUE THREAD

**Issue by bojevnim** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#6]
It's not working. I can apply everything but that. What's the problem?

**Comment by xAranaktu** [comment]
Some of the scripts are not working on latest game version. 

https://www.patreon.com/posts/latest-game-22247079

**Comment by bojevnim** [comment]
But it worked at first. One day it worked, the next day I wanna apply it, and can't.

**Comment by xAranaktu** [comment]
Game was updated on 23rd October. So if you played on Monday then it worked... Dunno what you don't get here.
