### ISSUE TITLE
Cannot open the database tables in v1.1.7

### ISSUE THREAD

**Issue by congmasosyu** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#60]
![image](https://user-images.githubusercontent.com/46387210/53679451-d50d6100-3d07-11e9-8fd9-60db28e82db0.png)

The version of Cheat Engine is 6.8.3, the v1.1.7 should has fixed the problem
Couldn't still open the database tables, same were other options

**Comment by xAranaktu** [comment]
Read [Getting Started](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table#getting-started)
