### ISSUE TITLE
edit player doesn't open

### ISSUE THREAD

**Issue by DCND-tom** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#61]
Hey, i can not open edit player or either edit existing job offers, what's wrong??
(I'm using 1.0.10)
![screenshot 64](https://user-images.githubusercontent.com/47943914/53691980-c5028980-3dba-11e9-9eca-2dec5fdadd7a.png)

**Comment by xAranaktu** [comment]
your game version is not fully compatible with the cheat table version your are using.
