### ISSUE TITLE
Cheat table 1.1.6 issue.

### ISSUE THREAD

**Issue by DariusS31** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#64]
Hi man, I love your work. Recently I downloaded your latest table for Fifa 19 (I used the older version) and I have a huge problem:
It doesn't work at all. The table loads in Cheat Engine(I have the newest version), but it doesn't allow me to activate any option and it shows me an error, something  like "Did you unzipped the archive?"
Also, that GUI doesn't load, but I don't know how to create that thing in Documents.
Can you help me?

**Comment by JesperJofficial** [comment]
same here

**Comment by JesperJofficial** [comment]
i found it. 
what i did is that i pasted the map from the zip to my files, and created a shortcut from the cheat table to my desktop. Now it doesnt give the error, because the cheat table is in the map it was originally
