### ISSUE TITLE
Picture change

### ISSUE THREAD

**Issue by JesperJofficial** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#65]
Hey man, I really like the cheat table and i'm having a lot of fun!
Could you maybe make a new option that allows you to change the pictures of the players in the squad hub? If this is possible, we could create accual icons. 
Hope that it's possible ;)

**Comment by FIFER-Mods** [comment]
You'll need frosty to change any graphics. And we can already add icons.

**Comment by JesperJofficial** [comment]
with the picture?

**Comment by FIFER-Mods** [comment]
Yes, with the minifaces. You can only do it with RDBM tho. Or download an
icon squad file.
