### ISSUE TITLE
My player career mode market value

### ISSUE THREAD

**Issue by hunter-mlenje** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#66]
Is it possible to edit my players market value? It would be nice to be able to edit this. And thanks for cheat table. Works like a charm.

**Comment by FIFER-Mods** [comment]
No, it's not.

**Comment by hunter-mlenje** [comment]
Would it be possible to edit? Could it happen?

**Comment by xAranaktu** [comment]
No. It's not stored anywhere. Game calculate it dynamically, so to edit value you need to edit your player attributes/potential/age/position.
