### ISSUE TITLE
Copy player from Futwiz

### ISSUE THREAD

**Issue by DidarFB** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#68]
When you gonna make possible to copy player stats from futwiz please do it

**Comment by xAranaktu** [comment]
Most probably in one of the April's update.

**Comment by DidarFB** [comment]
> Most probably in one of the April update.

nice

**Comment by DiegoAv26** [comment]
Could that also include copying from Futbin? Idk if there is a difference but thought I would add it to one of the already existing requests.

**Comment by xAranaktu** [comment]
> Could that also include copying from Futbin? Idk if there is a difference but thought I would add it to one of the already existing requests.

Well, it will work differently. I'll probably just try to use FUT API, so it will be easier and you will not need to copy and paste any links from futwiz.

**Comment by DidarFB** [comment]
please please release it quickly i can't wait for it

**Comment by xAranaktu** [comment]
Added in v1.2.7
[Release schedule](https://docs.google.com/spreadsheets/d/1EsYf4I4oDD6kw5jTGTFsv7rR1qL-Oausd1ZRbbSWm84/edit?usp=sharing)
![](https://i.imgur.com/UEAYqeo.gif)
