### ISSUE TITLE
EDITING PLAYER SCRIPS DON'T SEEM TO WORK ON v1.0.4

### ISSUE THREAD

**Issue by XOverdose** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#7]
So I just downloaded the latest version of your cheat table and I needed to edit a player's name.  However, when I click on the "Editing Player script" and "Edit Player" script, it doesn't seem to work as nothing would happen, not even the next sub-section showing up, as the X thingy at the left-hand side won't show up.  The same goes for the "Unlock edit player in career mode" thingy.  This did not seem to be a problem in v1.0.3 as I was able to do what I needed on that version but it's a problem with version, it's just with this version it has become a problem

**Comment by xAranaktu** [comment]
Same problem as in #6
