### ISSUE TITLE
REQ: Could you make the big AI teams field stronger sides in CM

### ISSUE THREAD

**Issue by marcoI992** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#70]

**Comment by marcoI992** [comment]
The big teams seem to field weak teams if there playing any team lower than them. ie in my last cm 20 games have gone and man city only played ederson 3 times and sterling and de bruyne 4 times this is the same for all big teams and now bournmouth are top of epl with 3 of the big 6 in the bottom half. TIA for a reply

**Comment by FIFER-Mods** [comment]
No, you need frosty for that.

**Comment by FIFER-Mods** [comment]
No, you need frosty for that.

**Comment by xAranaktu** [comment]
Ye, as FIFER said, this will require frosty tool to edit all .ini files which control it. Too much work to do it in CT.
