### ISSUE TITLE
Sugg: Older Players 

### ISSUE THREAD

**Issue by JoseLuisRuedaA** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#71]
Hi Aranaktu.

First of all thanks for the table. It's very heplful for the people who play carrer mode.

I wnat to know o make a request if it's possible, now that i'm using the lua script where everyone are 16 year old. If there's a posibility to make the older players not to retire. I mean in the table there are an option to change it, but if it can be possible with a new script instead of search all the player and change it manually.

Thanks.

**Comment by xAranaktu** [comment]
[Added to roadmap.](https://trello.com/b/rJNRwIP2/fifa-19-ct-roadmap)
