### ISSUE TITLE
Request for changing kit sponsors

### ISSUE THREAD

**Issue by Ricsss** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#72]
Hey, I would like to ask if it was possible to edit a kit sponsor. For example, change a team with NB as their sponsor and make it Nike; have a team with Fly emirates and change it to another one

**Comment by xAranaktu** [comment]
Since frosty tool supports editing game files it should be possible to edit kits in any way you want.
You probably will need Photoshop skills to edit them ofc.
Join [discord](https://discordapp.com/invite/cbQePsR). There are ppl who knows how to edit kits.
