### ISSUE TITLE
Modified Youth Players Don't Grow!!!

### ISSUE THREAD

**Issue by l0u1szz** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#73]
Hello,

I have two questions,

(1) I changed the body type and head id of my youth player, and add some positions he can play. Then I found none of his stats are growing even after three months. Is that because I modified him?

(2) What does Modifier in the table refer to? The value is usually 5, 6, or 7.

Thanks for your amazing work, and look forward to your replies!

Louis

**Comment by xAranaktu** [comment]
1. Did you changed his primary position? What's his age, potential and ovr? Editing player appearance will not affect his growth.

2. I don't know.

**Comment by l0u1szz** [comment]
Many thanks for reply.

He was 16yo RW and RM, 81 overall, and 95 potential. I added the third and fourth position as CAM and ST. Also, I changed his first, last, and nick name.

**Comment by xAranaktu** [comment]
So make a copy of this save and simulate a season or two and check if he will grow or not.

**Comment by xAranaktu** [comment]
But his ovr is pretty high. I guess you are training him. So, imo. it's normal that he is not growing.

**Comment by l0u1szz** [comment]
I followed your advice and simmed 2 seasons, but still no growth. Then I tried to change his age to 22, and after the third season, there was a 4 growth in overall. It seems that talents won't boost to 90+ overall before 20 yo. 

Thank you so much, and forgive my poor English.
