### ISSUE TITLE
player release

### ISSUE THREAD

**Issue by punkexx** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#75]
Hey Man

for some reason the Free and unlimited player release script dont work , i cant choose it
evey other script work for me only that one doesn't

can you help me please?

**Comment by FIFER-Mods** [comment]
What version of the table are you using? And are you using the cracked
version of FIFA?

**Comment by wanderers2804** [comment]
i'm too. 
when i use 1.2.9 table, it didn't work
i'm using FIFA 19 cpy version

**Comment by xAranaktu** [comment]
> i'm using FIFA 19 cpy version

Probably that's way. Try older CT versions.
