### ISSUE TITLE
Error:Chunk length exceeds stream length

### ISSUE THREAD

**Issue by yjm930504** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#77]
After i reinstalled my windows system, i got issue "Error:Chunk length exceeds stream length". I really don't know how to fix it.

**Comment by FIFER-Mods** [comment]
Try reinstalling cheat engine

**Comment by yjm930504** [comment]
not working. I also tried Cheat Engine 6.7

**Comment by xAranaktu** [comment]
Try to ask on CE forum. I've no idea what may cause this.
