### ISSUE TITLE
Req: to stop red and yellow cards shown in matches

### ISSUE THREAD

**Issue by ghbin59** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#78]
I like sliding, and often get too many yellow cards and red cards in matches, so it troubles me. Would it be possible to stop the referee from showing cards?

**Comment by xAranaktu** [comment]
You can disable bookings in game settings. 
![](https://i.imgur.com/AsN4JKi.png)

**Comment by ghbin59** [comment]
Your suggestion works. Thank you for help.
