### ISSUE TITLE
Remove Player

### ISSUE THREAD

**Issue by amanciofael** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#79]
How do I remove a FIFA Player?  and also how do I add a player who left the game? Thank you.

**Comment by FIFER-Mods** [comment]
RDBM, but it might crash

**Comment by amanciofael** [comment]
How do I remove it by RDBM? You have step by step how to remove the player.

________________________________
De: FIFER Mods (Lewis) <notifications@github.com>
Enviado: quinta-feira, 2 de maio de 2019 16:15
Para: xAranaktu/FIFA-19---Career-Mode-Cheat-Table
Cc: amanciofael; Author
Assunto: Re: [xAranaktu/FIFA-19---Career-Mode-Cheat-Table] Remove Player (#79)

RDBM, but it might crash

**Comment by FIFER-Mods** [comment]
Load your career, locate the player in all relevent tables (players,
teamplayerlinks are the main ones, but also check career_contract,
bannerplayers, loans) and delete all the rows with his id in it. For adding
players it's the opposite (will probably crash tho)

**Comment by amanciofael** [comment]
I tried here but I could not. could you include player Daniel Arzani on Celtic in that last update that happened? If I can, I'll be very grateful. Thank you.

________________________________
De: FIFER Mods (Lewis) <notifications@github.com>
Enviado: quinta-feira, 2 de maio de 2019 18:10
Para: xAranaktu/FIFA-19---Career-Mode-Cheat-Table
Cc: amanciofael; Author
Assunto: Re: [xAranaktu/FIFA-19---Career-Mode-Cheat-Table] Remove Player (#79)

Load your career, locate the player in all relevent tables (players,
teamplayerlinks are the main ones, but also check career_contract,
bannerplayers, loans) and delete all the rows with his id in it. For adding
players it's the opposite (will probably crash tho)

**Comment by FIFER-Mods** [comment]
The best way is to get him from your Youth academny with the new feature

>

**Comment by amanciofael** [comment]
I wanted to thank you, I managed to remove the player from the game, you are the best and thank you.

________________________________
De: FIFER Mods (Lewis) <notifications@github.com>
Enviado: sexta-feira, 3 de maio de 2019 20:01
Para: xAranaktu/FIFA-19---Career-Mode-Cheat-Table
Cc: amanciofael; Author
Assunto: Re: [xAranaktu/FIFA-19---Career-Mode-Cheat-Table] Remove Player (#79)

The best way is to get him from your Youth academny with the new feature

**Comment by FIFER-Mods** [comment]
No problem.
