### ISSUE TITLE
Change teams that already exists

### ISSUE THREAD

**Issue by Gohan4477** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#81]
Hi, can you add something so can we change the name or/and the logo of the teams that are already in Fifa? I would to change for example Paraná from the Brazilian league to Flamengo who isn't in the game.

Thanks!

**Comment by xAranaktu** [comment]
You can do this with frosty tool. (Don't ask me how, because I don't know)
https://frostytoolsuitedev.gitlab.io/
