### ISSUE TITLE
Can't Change Promoted Team's Number/Name Colours

### ISSUE THREAD

**Issue by ASAPPocky** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#82]
Issue is listed above. I edited a (EFL Championship) team's number and name colours and then when they were promoted (to the Premier League) the colours defaulted to what they were originally. I can't change them even using the Cheat Engine Table.

Using latest table with Origin version of game

**Comment by FIFER-Mods** [comment]
Edit competionkits table with RDBM

**Comment by ASAPPocky** [comment]
Excellent, worked perfectly! Thank you for all the work that you do! :)
