### ISSUE TITLE
AOB_MatchScore AOBScanModule error Issue

### ISSUE THREAD

**Issue by ghbin59** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#84]
Whenever I click"In-Game Hacks", my computer says:
![in-game hacks](https://user-images.githubusercontent.com/50183209/57529954-b9a67e00-7368-11e9-9c18-acf9856f9efc.png)
"AOB_MatchScore AOBScanModule error. Try to restart FIFA and Cheat Engine."

**Comment by xAranaktu** [comment]
Cheat table version you have is not fully compatible with your game version. Try older CT versions if you already have v1.2.8.
