### ISSUE TITLE
Unlimited players in club

### ISSUE THREAD

**Issue by JesperJofficial** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#86]
hey man, I was wondering if it is possible to change the max amount players in your club to unlimited or at least increase it. I think the max players right now is 50.
If this is possible, it would make you're cheat table even more fantastic :)

Jesper

**Comment by FIFER-Mods** [comment]
Not without it crashing

**Comment by xAranaktu** [comment]
Max is 52. I've tried but the game is crashing every time. Too many things to handle. It will not be added in FIFA 19 for sure.
