### ISSUE TITLE
Loading error! 

### ISSUE THREAD

**Issue by Wesleyyy1213** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#87]
When i start up cheat engine and cheat table.

its says lua error, and then it will say progam not working, then it crashes

**Comment by FIFER-Mods** [comment]
Go Edit < Settings and make sure "Allow table to execute lua scripts" is on
always.

**Comment by xAranaktu** [comment]
Read [Getting Started](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table#getting-started)
