### ISSUE TITLE
Copa Libertadores/FIFA Club World Cup

### ISSUE THREAD

**Issue by sebandresilva** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#88]
Can you do something to edit the name and number of teams of the tournaments? Career mode doesn't  have Copa Libertadores nor FIFA Club World Cup. The generic version of Copa Libertadores is "Copa Latina" and it doesn't even have the correct number of teams that participate in Copa Libertadores. Copa América is supposed to be "South American Cup", and EA also didn't add anything similar to FIFA Club World Cup. I don't know how hard something like that would be, but it would be really awesome to play a world final between Real Madrid and Gremio, Sao Paulo and Liverpool, Barcelona and River Plate. Latinamerican fans would love it!

**Comment by xAranaktu** [comment]
It will require to edit a lot of game files, which probably can be done with [Frosty Tool](https://frostytoolsuitedev.gitlab.io). It's definitely not a thing that can be implemented in the Cheat Table.
