### ISSUE TITLE
Req: Custom Transfer Offers

### ISSUE THREAD

**Issue by Nigelos** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#91]
First off, well done on your fantastic work.

I was wondering whether it is possible to introduce Custom Transfer Offers. What I mean is that when we receive an offer for one of our players, we can use Cheat Table to alter things like the club that is sending the offer (might be useful when I want my player to transfer to a specific club without having to Swap Transfer him which results in having to take a player from the destination club) or even maybe the transfer value offer figure?

Thanks in advance and I look forward to hearing from you!

**Comment by xAranaktu** [comment]
Feature which will allow you to transfer players between teams will be added soon.
