### ISSUE TITLE
Clone option problem

### ISSUE THREAD

**Issue by DegmanCRO** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#92]
Hi Aranaktu, amazing work, as always,

I have some "problems" with clone stats. I try it with some players but when its applied and saved i can see new stats in menu of career mode but when im playing match all stats from players are random...I mean on some players stats changing works but on some players it will be random in match. Is that bug or my bad? Thanks.

**Comment by xAranaktu** [comment]
You are doing something wrong.

**Comment by DegmanCRO** [comment]
I deleted old files and start all again,
Baumann from Hoffenheim have 83 i think,best card is 84,he have ingame(in match) 88 overall. I dont get it :(

In clone option card have 83 DIV 83 HAN 86 REF...but in Attributes option have all gk stats up to 10+

Now ill go try without updating career squads
