### ISSUE TITLE
Req: Editing the Board Manager

### ISSUE THREAD

**Issue by kelincipetarung** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#94]
Hy, xAranaktu!

Great work for the table!
I kinda wondering, is it possible to add a script to edit the board manager? Like, I want to edit current my Youth Development task to something easier, and maybe remove the task at all. Because, it so hard for me to complete them.

Well, i hope you reply soon. Thank You!

**Comment by xAranaktu** [comment]
"Edit objectives" is planned feature already. 
Please, check [FIFA 19 CT Roadmap](https://trello.com/b/rJNRwIP2/fifa-19-ct-roadmap) before you make a request.
