### ISSUE TITLE
Side Changes

### ISSUE THREAD

**Issue by SaeedRz96** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#97]
i want to use CPU v CPU mode in my manager career.i enabled it from this cheat table but it's not worked correctly. when i active this option it seems CPU and me (together) are playing against rival!
actually i should control some players. like when your friend and you are playing as same side !
what should i do for that?

**Comment by xAranaktu** [comment]
Change 'Controller ID' from 0 to '4' if you are playing on keyboard

**Comment by SaeedRz96** [comment]
Thanks man it worked :)
